flowchart LR
    INFO_000001["Order<br/><small>InformationObject</small>"]
    INFO_000002["Kund<br/><small>InformationObject</small>"]
    INFO_000003["Betalning<br/><small>InformationObject</small>"]
