flowchart LR
    ACT_000001["Kund<br/><small>Actor</small>"]
    EXT_000001["Payment Gateway<br/><small>ExternalSystem</small>"]
    EXT_000002["Delivery System<br/><small>ExternalSystem</small>"]
    SYS_000001["Order System<br/><small>System</small>"]
    ACT_000001 -->|uses| SYS_000001
