#!/usr/bin/env python3
from pathlib import Path
import argparse
import zipfile
import yaml

ROOT=Path(__file__).resolve().parents[1]

def member(zf,suffix):
    matches=[n for n in zf.namelist() if n.endswith("/"+suffix) or n==suffix]
    if len(matches)!=1:
        raise ValueError(f"expected one {suffix}, found {matches}")
    return matches[0]

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--artifact",required=True)
    a=ap.parse_args()
    artifact=Path(a.artifact)
    if not artifact.is_absolute():
        artifact=ROOT/artifact

    errors=[]
    project=yaml.safe_load((ROOT/"gpt-project.yaml").read_text(encoding="utf-8"))
    spec=yaml.safe_load((ROOT/"templates/custom-gpt-distribution.yaml").read_text(encoding="utf-8"))

    if not artifact.is_file():
        print(f"FAILED: missing Custom GPT ZIP: {artifact}")
        return 1

    with zipfile.ZipFile(artifact) as zf:
        if zf.testzip():
            errors.append("Custom GPT ZIP is corrupt")
        names=[n for n in zf.namelist() if not n.endswith("/")]

        required=["instructions.md","manifest.yaml"] + [
            f"knowledge/{item['output']}" for item in spec.get("knowledge",[])
        ]
        for req in required:
            try:
                member(zf,req)
            except ValueError as exc:
                errors.append(str(exc))

        try:
            inst=zf.read(member(zf,"instructions.md")).decode("utf-8")
            if len(inst)>8000:
                errors.append(f"Custom GPT instruction exceeds 8000 chars: {len(inst)}")
            folded=inst.casefold()
            for marker in [
                "inspect → validate → plan → change → validate → derive → package",
                "påstå aldrig att ett verktyg har körts",
                "unrun verification",
                "får aldrig redovisas som pass",
                "inte faktiskt har utförts",
                "kanonisk mutation stoppas",
                "kanoniska yaml-modellen",
            ]:
                if marker.casefold() not in folded:
                    errors.append(f"Custom GPT instruction missing 1.5 marker: {marker}")
        except ValueError as exc:
            errors.append(str(exc))

        try:
            manifest=yaml.safe_load(zf.read(member(zf,"manifest.yaml")).decode("utf-8")) or {}
            if manifest.get("distribution_type")!="custom_gpt":
                errors.append("Custom GPT manifest distribution_type mismatch")
            generated=manifest.get("generated",{})
            for rel,meta in generated.items():
                try:
                    data=zf.read(member(zf,rel))
                except ValueError as exc:
                    errors.append(str(exc))
                    continue
                if meta.get("bytes")!=len(data):
                    errors.append(f"generated byte size mismatch: {rel}")
        except ValueError as exc:
            errors.append(str(exc))

        forbidden={"/scripts/","/tests/","/distributions/"}
        for name in names:
            path="/"+name
            if any(x in path for x in forbidden):
                errors.append(f"Custom GPT contains forbidden runtime content: {name}")

    runtime=project["runtimes"]["custom_gpt"]
    parity=runtime["parity"]
    if runtime.get("local_tools")!="unavailable":
        errors.append("Custom GPT local_tools must remain unavailable")
    if parity.get("workspace_state")!="reduced":
        errors.append("Custom GPT workspace/state parity must remain reduced")
    if parity.get("tools")!="unavailable":
        errors.append("Custom GPT tool parity must remain unavailable")
    if parity.get("capabilities")!="ready_with_fallbacks":
        errors.append("Custom GPT capability parity must remain ready_with_fallbacks")

    if errors:
        print("FAILED: Custom GPT GPT Builder 1.5 verification")
        for e in errors: print("-",e)
        return 1

    print("OK: Custom GPT GPT Builder 1.5 verification")
    print("Instruction budget, Knowledge, reduced tool/workspace parity and no-false-PASS preserved")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
